#!/bin/bash

set -e

run()
{
  echo
  echo "*******************************"
  echo "* Starting dotfiles installer *"
  echo "*******************************"
  echo

  cd `dirname $0`
  symlink_files

  echo "********************************"
  echo "* Done with dotfiles installer *"
  echo "********************************"
}

symlink_files() {
  echo "Symlinking dotfiles..."
  files=(
  XCompose
  Xmodmap
  config/awesome
  config/fish
  config/nvim
  config/kitty
  gitconfig
  iex.exs
  oh-my-zsh/themes/lasseebert.zsh-theme
  oh-my-zsh/plugins/lasseebert/lasseebert.plugin.zsh
  profile
  tool-versions
  xbindkeysrc
  zshrc
  )
  for file in "${files[@]}"
  do
    symlink "`pwd`/$file" "$HOME/.$file"
  done

  echo
}

symlink() {
  file_path=$1
  link_path=$2
  link_dir=`dirname $link_path`

  if [ ! -d $link_dir ]
  then
    mkdir -pv $link_dir
  fi

  if [ -L $link_path ]
  then
    if [ "`readlink $link_path`" != "$file_path" ]
    then
      rm -rfv $link_path
      ln -sv $file_path $link_path
    else
      echo " [ OK ] $link_path"
    fi
  else
    if [ -a $link_path ]
    then
      mv $link_path $link_path.bak
    fi
    ln -sv $file_path $link_path
  fi
}

run
