#!/bin/bash

run()
{
  echo
  echo "*******************************"
  echo "* Starting dotfiles installer *"
  echo "*******************************"
  echo

  cd `dirname $0`
  install_essentials
  git_pull
  install_ohmyzsh
  switch_to_zsh

  echo "********************************"
  echo "* Done with dotfiles installer *"
  echo "********************************"
}

switch_to_zsh() {
  echo "Checking if zsh is used"
  result=$(cat /etc/passwd | grep `whoami` | grep `which zsh`)
  if [ "$result" = "" ]
  then
    echo " [ NO ]"
    chsh -s `which zsh`
    echo " Changed shell to `which zsh`"
  else
    echo " [ OK ] `which zsh`"
  fi
  echo
}

install_ohmyzsh() {
  echo Checking for oh-my-zsh...
  if [ ! -d ~/.oh-my-zsh ]
  then
    echo " Installing oh-my-zsh..."
    curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
  else
    echo " [ OK ] Installed"
  fi
  echo
}

git_pull()
{
  echo "Updating repo..."

  echo " git pull"
  git pull

  echo " git submodule init"
  git submodule init

  echo " git submodule update"
  git submodule update

  echo
}


install_essentials()
{
  packages=( git zsh vim-gnome libffi-dev libssl-dev zlib1g-dev libreadline-dev libxslt1-dev libxml2-dev libmysql-ruby libmysqlclient-dev libmagickwand-dev libsqlite3-dev )
  echo "Checking for essential packages..."
  for package in "${packages[@]}"
  do
    install_package $package
  done
  echo
}

install_package()
{
  package=$1
  PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $package|grep "install ok installed")
  if [ "" == "$PKG_OK" ]; then
    echo "$package not installed. Installing now."
    sudo apt-get --force-yes --yes install $package
  else
    echo " [ OK ] $package"
  fi
}

run
